### ISSUE TITLE
improve ipfjes-interview 'front page' so it's clear what I can do as a user

### ISSUE THREAD

**Issue by drcjar** [drcjar/ipfjes-interview#33]
this will be

1. find a research participant and review/edit their interview/other details 
2. add a new research participant

for users rupa and carl

**Comment by davidmiller** [comment]
I think you can do this from the menu... e.g. you can search, add or look at people to interview.

I'm not sure this app needs a splash screen - at least for now. 

Would prob. redirect to search 

once you had a dashboard, you could start with that
