### ISSUE TITLE
asbestos exposure assessment should be faithful to content of Cherrie method

### ISSUE THREAD

**Issue by drcjar** [drcjar/ipfjes-interview#53]
Including near/ far field and active/passive emissions.

Have flip flopped on this. Apologies.

Rationale is that while likely we will not use some aspects of (or we think they won't affect model) it's the whole that has been validated so better to include at least initially.

**Comment by davidmiller** [comment]
This isn't really enough information to implement... 

What do you mean ? 

Near/Far field is already there.
Either I've completely misunderstood the entire thing, or active emissions are already there.

Assuming I haven't, what exactly would you like done to include passive emissions ?

**Comment by drcjar** [comment]
I have in mind completing the implementation of John Cherries assessment as described by his spreadsheet e.g

![image](https://cloud.githubusercontent.com/assets/507188/25814948/171202dc-3417-11e7-912c-ff4791739a02.png)

**Comment by davidmiller** [comment]
Right, but um, can you phrase that in terms of what 'completing the implementation' would entail ? :) 

e.g. What are the missing things from the most recent iteration of the form that you would like to be there?
