### ISSUE TITLE
lets have a way of removing a participant from the list of particpants to call and recording the reason

### ISSUE THREAD

**Issue by drcjar** [drcjar/ipfjes-interview#80]
e.g no longer wishes to take part, died, no response after 3 attempts, other (specify)

**Comment by davidmiller** [comment]
So: Remove the `needs_interview` tag and add an additional data entry step (this will require a database schema update obv.) - sounds fairly sensible.

If the list is too cluttered short term you can archive the tag in the admin to make them no longer appear on the list...
